//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlaceModel()
        {
            this.MostWantedPlaces = new HashSet<MostWantedPlaceModel>();
            this.PlacesPhotos = new HashSet<PlacesPhotoModel>();
            this.UserSearchHistories = new HashSet<UserSearchHistoryModel>();
            this.PlacesReviews = new HashSet<PlacesReviewModel>();
        }
    
        public int IdPlace { get; set; }
        public string Type { get; set; }
        public Nullable<int> IdCity { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public string Telephone { get; set; }
        public string Website { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<double> RatingFloat { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public Nullable<System.TimeSpan> OpenTime { get; set; }
        public Nullable<System.TimeSpan> CloseTime { get; set; }
        public Nullable<bool> Confirmed { get; set; }
        public string IdPartner { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        public virtual CityModel City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MostWantedPlaceModel> MostWantedPlaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlacesPhotoModel> PlacesPhotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSearchHistoryModel> UserSearchHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlacesReviewModel> PlacesReviews { get; set; }
    }
}
