//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlacesReviewModel
    {
        public int IdReview { get; set; }
        public int IdPlace { get; set; }
        public string IdUser { get; set; }
        public string EmailUser { get; set; }
        public string Review { get; set; }
        public int Rating { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual PlaceModel Place { get; set; }
    }
}
