//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesContext : DbContext
    {
        public EntitiesContext()
            : base("name=EntitiesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<MostWantedPlace> MostWantedPlaces { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<PlacesPhoto> PlacesPhotos { get; set; }
        public virtual DbSet<PlacesType> PlacesTypes { get; set; }
        public virtual DbSet<UserSearchHistory> UserSearchHistories { get; set; }
        public virtual DbSet<PlacesReview> PlacesReviews { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    }
}
